FROM parrotsec/security

ENV DEBIAN_FRONTEND noninteractive
ENV TERM xterm-256color


RUN git clone https://github.com/tmux-plugins/tmux-logging /opt/tmux-logging/

# Enable SSH
RUN sudo update-rc.d -f ssh remove && \
  sudo update-rc.d -f ssh defaults && \
  sudo service ssh restart && \
  sudo update-rc.d -f ssh enable 2 3 4 5

ENTRYPOINT ["/bin/bash"]
